---
- name: create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ bat_download_dir }}'

- name: download bat
  ansible.builtin.get_url:
    url: '{{ bat_redis_url }}'
    checksum: 'sha256:{{ bat_redis_sha256sum }}'
    dest: '{{ bat_download_dir }}/{{ bat_redis_filename }}'
    force: no
    mode: 'u=rw,go=r'

- name: install bat
  become: yes
  ansible.builtin.apt:
    deb: '{{ bat_download_dir }}/{{ bat_redis_filename }}'
