# code: language=ansible
---
- name: Create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ bat_download_dir }}'

- name: Download bat
  ansible.builtin.get_url:
    url: '{{ bat_redis_url }}'
    checksum: 'sha256:{{ bat_redis_sha256sum }}'
    dest: '{{ bat_download_dir }}/{{ bat_redis_filename }}'
    force: false
    mode: 'u=rw,go=r'

- name: Install bat
  become: true
  block:
    - name: Install bat from local file
      ansible.builtin.apt:
        deb: '{{ bat_download_dir }}/{{ bat_redis_filename }}'
        state: 'present'
  rescue:
    - name: Install xz-utils as deb requirements
      ansible.builtin.apt:
        package: 'xz-utils'
        state: 'present'

    - name: Make sure system is ready for selected bat version and remove bat
      ansible.builtin.apt:
        package: 'bat'
        state: 'absent'

    - name: Install remote
      ansible.builtin.apt:
        deb: '{{ bat_download_dir }}/{{ bat_redis_filename }}'
        state: 'present'
