---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible_role_bat_ubuntu_max
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: ubuntu_max

verifier:
  name: testinfra
  directory: ../default/tests
